import { Toast, AppState } from '../app.js';
import { ExportEngine } from '../core/export.js';

export default {
  render(container) {
    container.innerHTML = `
      <div class="flex h-full gap-6 fade-in">
        <div class="w-1/3 glass-card flex flex-col gap-4 p-5">
          <h2 class="text-xl font-bold mb-2">Report Config</h2>
          
          <label class="text-sm font-semibold">Title</label>
          <input type="text" id="rep-title" class="p-2 bg-gray-800 rounded border border-gray-600 text-white" value="Executive Summary">
          
          <label class="text-sm font-semibold mt-2">AI Provider</label>
          <select id="ai-provider" class="p-2 bg-gray-800 rounded border border-gray-600 text-white">
            <option value="gemini">Google Gemini</option>
            <option value="openai">OpenAI GPT-4o</option>
            <option value="anthropic">Anthropic Claude</option>
            <option value="cohere">Cohere Command-R</option>
            <option value="ollama">Ollama (Local)</option>
          </select>
          
          <div id="api-key-container" class="flex flex-col gap-1">
            <label class="text-sm font-semibold mt-2">API Key</label>
            <input type="password" id="ai-key" class="p-2 bg-gray-800 rounded border border-gray-600 text-white" placeholder="Enter API Key">
          </div>
          
          <div id="model-container" class="hidden flex flex-col gap-1">
            <label class="text-sm font-semibold mt-2">Model Name</label>
            <input type="text" id="ai-model" class="p-2 bg-gray-800 rounded border border-gray-600 text-white" placeholder="llama3, mistral, etc.">
          </div>
          
          <label class="text-sm font-semibold mt-2">Context / Notes</label>
          <textarea id="rep-notes" class="p-2 bg-gray-800 rounded border border-gray-600 text-white h-24" placeholder="What should the report focus on?"></textarea>
          
          <button id="btn-generate" class="btn btn-primary mt-4 py-3 text-lg font-bold">Generate Report</button>
        </div>
        
        <div class="w-2/3 glass-card flex flex-col p-5">
          <div class="flex justify-between items-center border-b border-gray-700 pb-3 mb-4">
            <h2 class="text-xl font-bold">Report Viewer</h2>
            <div class="flex gap-2">
              <button id="btn-pdf" class="btn btn-secondary text-sm">Export PDF</button>
              <button id="btn-pptx" class="btn btn-secondary text-sm">Export PPTX</button>
            </div>
          </div>
          <div id="report-content" class="flex-grow overflow-y-auto prose prose-invert max-w-none text-gray-300">
            <p class="text-center text-gray-500 italic mt-20">Click Generate to create an AI-powered report based on your data.</p>
          </div>
        </div>
      </div>
    `;

    const providerSel = container.querySelector('#ai-provider');
    const keyCont = container.querySelector('#api-key-container');
    const modelCont = container.querySelector('#model-container');
    const keyInp = container.querySelector('#ai-key');
    const modelInp = container.querySelector('#ai-model');

    const updateUI = () => {
      const p = providerSel.value;
      if (p === 'ollama') {
        keyCont.classList.add('hidden');
        modelCont.classList.remove('hidden');
        modelInp.value = localStorage.getItem('manz_model_ollama') || '';
      } else {
        keyCont.classList.remove('hidden');
        modelCont.classList.add('hidden');
        keyInp.value = localStorage.getItem(`manz_key_${p}`) || '';
      }
    };

    providerSel.addEventListener('change', updateUI);
    // Initialize
    providerSel.value = localStorage.getItem('manz_ai_provider') || 'gemini';
    updateUI();

    container.querySelector('#btn-generate').onclick = () => {
      const p = providerSel.value;
      localStorage.setItem('manz_ai_provider', p);
      if (p === 'ollama') localStorage.setItem('manz_model_ollama', modelInp.value);
      else localStorage.setItem(`manz_key_${p}`, keyInp.value);

      const content = container.querySelector('#report-content');
      content.innerHTML = `<div class="flex items-center justify-center h-full text-blue-400 animate-pulse text-lg">Generating report with ${p}...</div>`;
      
      // Simulate API call
      setTimeout(() => {
        content.innerHTML = `
          <h2>${document.getElementById('rep-title').value}</h2>
          <p>Generated by ${p}.</p>
          <h3>Key Insights</h3>
          <ul>
            <li>Revenue increased by 15% this quarter.</li>
            <li>Cost optimization improved margins by 3%.</li>
          </ul>
        `;
        Toast.success('Report generated successfully.');
      }, 1500);
    };

    container.querySelector('#btn-pdf').onclick = () => ExportEngine.exportPDF();
    container.querySelector('#btn-pptx').onclick = () => ExportEngine.exportPPTX();
  }
};
